require("util")
require("options")
require("plugins")
require("code")
require("text")
require("ui")
require("components")
require("keymaps")

keymap("n", "gd", "<cmd>Telescope lsp_definitions<cr>")
keymap("n", "gr", "<cmd>Telescope lsp_references<cr>")
